#!/bin/sh
. /lib/functions.sh

# 三频全开
uci set wireless.radio0.disabled='0'
uci set wireless.radio1.disabled='0'
uci set wireless.radio2.disabled='0'

# 5.8G（radio0）→ OpenWRT-5G
uci set wireless.default_radio0.ssid='OpenWRT-5G'
uci set wireless.default_radio0.encryption='psk2'
uci set wireless.default_radio0.key='12345678'
uci set wireless.default_radio0.disabled='0'

# 2.4G（radio1）→ OpenWRT
uci set wireless.default_radio1.ssid='OpenWRT'
uci set wireless.default_radio1.encryption='psk2'
uci set wireless.default_radio1.key='12345678'
uci set wireless.default_radio1.disabled='0'

# 5.2G 160M（radio2）→ OpenWRT-5G+
uci set wireless.default_radio2.ssid='OpenWRT-5G+'
uci set wireless.default_radio2.encryption='psk2'
uci set wireless.default_radio2.key='12345678'
uci set wireless.default_radio2.disabled='0'

uci commit wireless
exit 0
